### ISSUE TITLE
DraftRepository is missing

### ISSUE THREAD

**Issue by Exsaveron** [Schlaefer/phileAdminMarkdownEditor#3]
Hi,
i try to setup the MarkDowneditor. Unfortunately it only shows a white page after clicking "pages" in the admin area.
I tried to find the error myself but for now i did not succeed.
Anyway i checked the _PhileAdminMarkdownEditor.php_ and there is this use statement:

`use Phile\Plugin\Siezi\PhileAdminMarkdownEditor\Lib\DraftRepository`

but this file is not available in your Lib folder

FYI: The Admin Cache plug in works in my installation.

**Comment by Schlaefer** [comment]
> use Phile\Plugin\Siezi\PhileAdminMarkdownEditor\Lib\DraftRepository

This is not longer necessary, but shouldn't cause any errors. If you're using Phile 1.6 it's probably the same issue as #2. I'll look into that.

**Comment by Exsaveron** [comment]
Okay. Thanks for the info.
